package book.discount
import com.example.portalback.people.model.PeopleModel


rule "规则"

        when
            eval(true)
        then
            System.out.println("1243");
end

rule "规则2"

        when
            eval(true)
        then
            System.out.println("234");
end

rule "规则3"

        when
            PeopleModel(age=="14")
        then
            System.out.println("werw");
end