// 当前规则文件用来评估用户贷款背景分数
package creditCardApply;
import com.example.portalback.drools.model.*
dialect "java"

// 用户合法性检查 
rule "没房没车，学历大专以下，月薪少于5000，直接不通过"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==false,education==CreditCardApplyInfo.EDUCATION_1,monthlyIncome<5000)
    then
        $c.setCheckResult(false);
        $c.setScore(-1);
        drools.halt(); // 直接终止规则
end

rule "没车没房，学历专科，月薪大于一万，分数60分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==false,education==CreditCardApplyInfo.EDUCATION_2,monthlyIncome>=10000)
    then
        $c.setCheckResult(true);
        $c.setScore(70);
end

rule "没车没房，学历本科，月薪大于一万，分数65分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==false,education==CreditCardApplyInfo.EDUCATION_4,monthlyIncome>=10000)
    then
        $c.setCheckResult(true);
        $c.setScore(70);
end

rule "没车没房，学历本科以上，月薪大于一万，分数71分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==false,education==CreditCardApplyInfo.EDUCATION_4,monthlyIncome>=10000)
    then
        $c.setCheckResult(true);
        $c.setScore(70);
end


rule "没车没房，学历本科以上，月薪大于一万，分数72分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==false,education==CreditCardApplyInfo.EDUCATION_4,monthlyIncome>=10000)
    then
        $c.setCheckResult(true);
        $c.setScore(70);
end

rule "没车有房，学历本科以上，月薪大于一万，分数80分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==true,education==CreditCardApplyInfo.EDUCATION_4,monthlyIncome>=10000)
    then
        $c.setCheckResult(true);
        $c.setScore(80);
end

rule "有车没房，学历本科以上，月薪大于一万，分数75分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==false,hasCar==true,education==CreditCardApplyInfo.EDUCATION_4,monthlyIncome>=10000)
    then
        $c.setCheckResult(true);
        $c.setScore(75);
end

rule "有车有房，学历本科以上，月薪大于两万，分数90分"
    salience 100
    no-loop true
    when
        $c:CreditCardApplyInfo(hasHouse==true,hasCar==true,education==CreditCardApplyInfo.EDUCATION_4,monthlyIncome>=20000)
    then
        $c.setCheckResult(true);
        $c.setScore(90);
        $c.setQuota(100000);
end